### PR TITLE
Fix #2 - Add ability to enable and disable the system Spell Checker

### LINKED ISSUE #2: Disable spell-checker
Another source for flakyness in tests is the spell-checker as this can pop-up suggestions and then tests fail. So my suggestion for an enhancement would be to disable spell-checking like animations

### PR DESCRIPTION
**Pull request by kkoser**
This adds the ability to toggle the spell checker setting for tests. This is useful as sometimes the spell checker dialog can appear during tests and cause tests to fail.

No tests were added for this feature in this commit. Testing the spell checker is difficult to automate -- Android allows you to provide a replacement for the system spell checker, but it must be manually enabled by the user. Adding code to allow this in tests would add more code that could break, making the test more dangerous than productive.

### CODE REVIEW

File: test-butler-app/src/main/java/com/linkedin/android/testbutler/ButlerService.java [hunk 1]
```diff
@@ -114,6 +120,11 @@ public void onCreate() {
         gsmDataDisabler = new GsmDataDisabler();
         permissionGranter = new PermissionGranter();
 
+        spellCheckerDisabler = new SpellCheckerDisabler();
+        spellCheckerDisabler.saveLocationServicesState(getContentResolver());
```
Comment (drewhannay) [inline test-butler-app/src/main/java/com/linkedin/android/testbutler/ButlerService.java]: `saveLocationServicesState`?

File: test-butler-app/src/main/java/com/linkedin/android/testbutler/ButlerService.java [hunk 2]
```diff
@@ -140,6 +151,9 @@ public void onDestroy() {
 
         // Uninstall our IActivityController to resume normal Activity behavior
         NoDialogActivityController.uninstall();
+
+        // Reset the spell checker to the original state
+        spellCheckerDisabler.restoreLocationServicesState(getContentResolver());
```
Comment (drewhannay) [inline test-butler-app/src/main/java/com/linkedin/android/testbutler/ButlerService.java]: `restoreLocationServicesState`? 😂

File: CHANGELOG.md [hunk 3]
```diff
@@ -1,5 +1,8 @@
 # Change Log
 
+## Version 1.2.0-SNAPSHOT
+- Add api for enabling and disabling the spell checker during tests
```
Comment (drewhannay) [inline CHANGELOG.md]: Maybe one more line, `Disable spell checker by default during tests`?
